######################## default configuration ####################
baseURL=""
title="Hikari AI - Cloud Computing, Robotics, Edge AI, IoT, and more"
theme="bookworm-light"
# post pagination
paginate="5"
# post excerpt
summaryLength="40"
autoHeadingID="true"

############################# Modules ##############################

[module.hugoVersion]
extended = true
min="0.80.0"

############################# Outputs ##############################

[outputs]
home=["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe=true


############################## Plugins ##############################

pygmentsUseClasses=true
# Syntax Highlight
[markup.highlight]
  anchorLineNos=false
  codeFences=true
  guessSyntax=true
  hl_Lines=''
  lineAnchors=''
  lineNoStart=1
  lineNos=true
  lineNumbersInTable=false
  noClasses=false
  style='emacs'
  tabWidth=4

# Table of Contents
[markup.tableOfContents]
  startLevel=3
  endLevel=4
  ordered=false

# CSS Plugins
[[params.plugins.css]]
link="plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link="plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link="https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap"

# JS Plugins
[[params.plugins.js]]
link="plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link="plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link="plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link="plugins/search/fuse.min.js"
[[params.plugins.js]]
link="plugins/search/mark.js"
[[params.plugins.js]]
link="plugins/search/search.js"

# site variables
[params.variables]
font_primary="Mulish"
h1="64px"
h1_lg="52px"
h1_md="42px"
h2="38px"
h2_md="30px"
h3="30px"
h3_md="24px"
h4="24px"
h5="18px"
h6="16px"
white="#ffffff"
black="#000000"
dark="#141A26"
gray="#747577"
light="#FAFAFA"
color_primary="#5E498C"

#################### default parameters ################################

[params]
  logo="images/logo.png"
  images=["images/logo.png"]
  twitterUsername = "@lucaslongggg"
  socialImage = "images/logo.png"
  logo_height="55px"
  favicon="images/favicon.png"
  description="Cloud Computing, Robotics, Edge AI, IoT, and more"
  author="Kevin Yu"
  contact_form_action="#" # contact form works with https://formspree.io
  search=true
  mainSections=["blog"]
  copyright="Copy Right ©2019  🤍 Kevin Yu -- Theme made by Bookworm powered by Hugo"
  customCSS=["css/custom.css", "css/syntax.css"]

# Preloader
[params.preloader]
enable=false
preloader="" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable=true
# mailchimp subsciption
mailchimp_form_action="https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name="b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours
title="Subscribe for newsletter."
input_placeholder="Enter your email"

# cookies
[params.cookies]
enable=false
expire_days=2


############################# Main Menu ########################

[[menu.main]]
identifier="Home"
name="Home"
url="/"
weight=1

[[menu.main]]
name="Blog"
identifier="Blog"
url="categories/"
weight =2

  [[menu.main]]
  parent="Blog"
  name="Artifical Intelligence"
  url="categories/artificial-intelligence/"
  weight=1

  [[menu.main]]
  parent="Blog"
  name="Cloud Computing"
  url="categories/cloud-computing/"
  weight=2

  [[menu.main]]
  parent="Blog"
  name="DevOps"
  url="categories/devops/"
  weight=3

  [[menu.main]]
  parent="Blog"
  name="Linux"
  url="categories/linux"
  weight=4

  [[menu.main]]
  parent="Blog"
  name="Software"
  url="categories/software"
  weight=5

  [[menu.main]]
  parent="Blog"
  name="IoT"
  url="categories/iot"
  weight=6

[[menu.main]]
name="Page"
identifier="Page"
weight=3
url="#"
hasChildren=true

  [[menu.main]]
  parent="Page"
  name="Category"
  url="categories/"
  weight=1

  [[menu.main]]
  parent="Page"
  name="Tags"
  url="tags/"
  weight=2

  [[menu.main]]
  parent="Page"
  name="Terms & Conditions"
  url="terms-conditions/"
  weight=3

  [[menu.main]]
  parent="Page"
  name="Privacy"
  url="privacy/"
  weight=4

[[menu.main]]
name="About"
identifier ="About"
url="about/"
weight=4

############################# Footer Menu ########################

[[menu.footer]]
name="About"
url="about/"
weight=1

[[menu.footer]]
name="Terms & Conditions"
url="terms-conditions/"
weight=2

[[menu.footer]]
name="Privacy"
url="privacy/"
weight=3

# Social Icons
[[params.social]]
icon="las la-link" # https://icons8.com/line-awesome
url="https://link.hikariai.net"

[[params.social]]
icon="lab la-github" # https://icons8.com/line-awesome
url="https://github.com/yqlbu"

[[params.social]]
icon="lab la-discord" # https://icons8.com/line-awesome
url="https://discord.gg/hyNwvjtBJ7"

[[params.social]]
icon="lab la-telegram" # https://icons8.com/line-awesome
url="https://t.me/hikariai_channel"

[[params.social]]
icon="lab la-linkedin-in" # https://icons8.com/line-awesome
url="https://www.linkedin.com/in/chinglong-kevin-yu"
